version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: golmaster_postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: golmaster
      POSTGRES_USER: golmaster
      POSTGRES_PASSWORD: golmaster123
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
